### ISSUE TITLE
FOV is broken (kinda)

### ISSUE THREAD

**Issue by Xylemon** [eukos16/NGUNIX#10]
When virtual resolution is set to "low" weapons match their position with the original Quake. However when set to "normal" it looks way too low.

**Comment by eukos16** [comment]
I cannot seem to reproduce this. Might depend on the resolution you are playing at.

**Comment by Xylemon** [comment]
I've tested this on 4:3 640x480 and 16:9 1600x900 and I see the same results. What is your aspect method? I see this with hor+ HM and hor+ Qspasm but -vert looks weird all the time.

**Comment by leilei-** [comment]
I actually fixed this in my 486experiment branch.

**Comment by Xylemon** [comment]
Closing this since the HUD changes bring in a different problem and a variety of options that make this kinda obsolete.
