### ISSUE TITLE
Restrict Loading of Certain Files to Mod Directory

### ISSUE THREAD

**Issue by Xylemon** [eukos16/NGUNIX#17]
Please restrict files like the light, vis, and rtlights to the mod directory. By default NGUNIX loads these from the id1 folder and applies them to the mod you're currently playing. This should be fixed as soon as possible.

**Comment by eukos16** [comment]
Keep in mind that any minor modification will be affected by this as well and you'd end up with tons of duplicate files, maybe I can add a cvar for a workaround or something

**Comment by Xylemon** [comment]
OK, I've learned this is already implemented: Just go under "Advanced Options" and disable External Data for the mod that is having trouble with loading default lit and other files. So this is can be closed.
