### ISSUE TITLE
Awful mouse input

### ISSUE THREAD

**Issue by Xylemon** [eukos16/NGUNIX#2]
Mouse input is pretty awful and does some awfully weird things (due to old limitations?):

1) Moving around the mouse seems to be slow and stuck half the time.
2) If you minimize the client then bring it back up, it will freeze if you hold any mouse buttons and unfreeze upon letting go.

**Comment by Xylemon** [comment]
Update, the choppiness of the mouse is related to using a bigger resolution (like 1080p). Input lag?

**Comment by eukos16** [comment]
The framerate is just too slow.
Happens with crap processor (x86) on an overkill resolution
